/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as TripRouteImport } from './routes/trip'
import { Route as DestinationIdRouteImport } from './routes/destination.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const TripRoute = TripRouteImport.update({
  id: '/trip',
  path: '/trip',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationIdRoute = DestinationIdRouteImport.update({
  id: '/destination/$id',
  path: '/destination/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/plan': typeof PlanRoute
  '/rewards': typeof RewardsRoute
  '/trip': typeof TripRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/plan': typeof PlanRoute
  '/rewards': typeof RewardsRoute
  '/trip': typeof TripRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRoute
  '/explore': typeof ExploreRoute
  '/leaderboard': typeof LeaderboardRoute
  '/plan': typeof PlanRoute
  '/rewards': typeof RewardsRoute
  '/trip': typeof TripRoute
  '/destination/$id': typeof DestinationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/challenges'
    | '/explore'
    | '/leaderboard'
    | '/plan'
    | '/rewards'
    | '/trip'
    | '/destination/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/challenges'
    | '/explore'
    | '/leaderboard'
    | '/plan'
    | '/rewards'
    | '/trip'
    | '/destination/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/challenges'
    | '/explore'
    | '/leaderboard'
    | '/plan'
    | '/rewards'
    | '/trip'
    | '/destination/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRoute
  ExploreRoute: typeof ExploreRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PlanRoute: typeof PlanRoute
  RewardsRoute: typeof RewardsRoute
  TripRoute: typeof TripRoute
  DestinationIdRoute: typeof DestinationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip': {
      id: '/trip'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$id': {
      id: '/destination/$id'
      path: '/destination/$id'
      fullPath: '/destination/$id'
      preLoaderRoute: typeof DestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRoute,
  ExploreRoute: ExploreRoute,
  LeaderboardRoute: LeaderboardRoute,
  PlanRoute: PlanRoute,
  RewardsRoute: RewardsRoute,
  TripRoute: TripRoute,
  DestinationIdRoute: DestinationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
